# Lab: Titanic Survival Exploration with Decision Trees

## First setup the colab configuration to access google drive location 
**I'm using `colaboratory` (colab) for this notebook so you need to import drive from google.colab and mount your drive to access google drive. All datasets and notebook files I've already uploaded into `colabspace` folder of my google drive**

In [9]:
from google.colab import drive
# Here, you've to authentication verification, to do that just click given link and and copy key and paste it and hit enter
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [10]:
#checked current working directory
!pwd

/content


In [11]:
# change directory to your workspace in my case colabspace/src
%cd gdrive/MyDrive/colabspace/MachineLearningProject/src/

/content/gdrive/MyDrive/colabspace/MachineLearningProject/src


## Getting Started
In this lab, you will see how decision trees work by implementing a decision tree in sklearn.

We'll start by loading the dataset and displaying some of its rows.

In [12]:
# Import libraries necessary for this project
import numpy as np
import pandas as pd
from IPython.display import display # Allows the use of display() for DataFrames

# Pretty display for notebooks
%matplotlib inline

# Set a random seed
import random
random.seed(42)

# Load the dataset
# goto your drive and just copy path where your dataset is availabe 
in_file = '/content/gdrive/MyDrive/colabspace/MachineLearningProject/src/datasets/titanic_data.csv'
full_data = pd.read_csv(in_file)
# Print the first few entries of the RMS Titanic data
display(full_data.head())

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

Recall that these are the various features present for each passenger on the ship:
- **Survived**: Outcome of survival (0 = No; 1 = Yes)
- **Pclass**: Socio-economic class (1 = Upper class; 2 = Middle class; 3 = Lower class)
- **Name**: Name of passenger
- **Sex**: Sex of the passenger
- **Age**: Age of the passenger (Some entries contain `NaN`)
- **SibSp**: Number of siblings and spouses of the passenger aboard
- **Parch**: Number of parents and children of the passenger aboard
- **Ticket**: Ticket number of the passenger
- **Fare**: Fare paid by the passenger
- **Cabin** Cabin number of the passenger (Some entries contain `NaN`)
- **Embarked**: Port of embarkation of the passenger (C = Cherbourg; Q = Queenstown; S = Southampton)

Since we're interested in the outcome of survival for each passenger or crew member, we can remove the **Survived** feature from this dataset and store it as its own separate variable `outcomes`. We will use these outcomes as our prediction targets.  
Run the code cell below to remove **Survived** as a feature of the dataset and store it in `outcomes`.

In [13]:
# Store the 'Survived' feature in a new variable and remove it from the dataset
outcomes = full_data['Survived']
features_raw = full_data.drop('Survived', axis = 1)

# Show the new dataset with 'Survived' removed
display(features_raw.head())

PassengerId  Pclass  ... Cabin Embarked
0            1       3  ...   NaN        S
1            2       1  ...   C85        C
2            3       3  ...   NaN        S
3            4       1  ...  C123        S
4            5       3  ...   NaN        S

[5 rows x 11 columns]

The very same sample of the RMS Titanic data now shows the **Survived** feature removed from the DataFrame. Note that `data` (the passenger data) and `outcomes` (the outcomes of survival) are now *paired*. That means for any passenger `data.loc[i]`, they have the survival outcome `outcomes[i]`.

## Preprocessing the data

Now, let's do some data preprocessing. First, we'll one-hot encode the features.

In [14]:
features = pd.get_dummies(features_raw)

And now we'll fill in any blanks with zeroes.

In [15]:
features = features.fillna(0.0)
display(features.head())

PassengerId  Pclass   Age  ...  Embarked_C  Embarked_Q  Embarked_S
0            1       3  22.0  ...           0           0           1
1            2       1  38.0  ...           1           0           0
2            3       3  26.0  ...           0           0           1
3            4       1  35.0  ...           0           0           1
4            5       3  35.0  ...           0           0           1

[5 rows x 1730 columns]

## Training the model

Now we're ready to train a model in sklearn. First, let's split the data into training and testing sets. Then we'll train the model on the training set.

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(features, outcomes, test_size=0.2, random_state=42)

In [17]:
# Import the classifier from sklearn
from sklearn.tree import DecisionTreeClassifier

# Define the classifier, and fit it to the data
model= DecisionTreeClassifier()
model.fit(X_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

## Testing the model
Now, let's see how our model does, let's calculate the accuracy over both the training and the testing set.

In [18]:
# Making predictions
y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

# Calculate the accuracy
from sklearn.metrics import accuracy_score
train_accuracy = accuracy_score(y_train, y_train_pred)
test_accuracy = accuracy_score(y_test, y_test_pred)
print('The training accuracy is', train_accuracy)
print('The test accuracy is', test_accuracy)

The training accuracy is 1.0
The test accuracy is 0.7988826815642458


# Exercise: Improving the model

Ok, high training accuracy and a lower testing accuracy. We may be overfitting a bit.

So now it's your turn to shine! Train a new model, and try to specify some parameters in order to improve the testing accuracy, such as:
- `max_depth`
- `min_samples_leaf`
- `min_samples_split`

You can use your intuition, trial and error, or even better, feel free to use Grid Search!

**Challenge:** Try to get to 85% accuracy on the testing set. If you'd like a hint, take a look at the solutions notebook next.

In [19]:
from sklearn.tree import DecisionTreeClassifier

# Define the classifier, and fit it to the data
model = DecisionTreeClassifier(max_depth=6, min_samples_leaf=6, min_samples_split=10)
model.fit(X_train,y_train)


DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=6, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=6, min_samples_split=10,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [20]:
y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

# Calculate the accuracy
from sklearn.metrics import accuracy_score
train_accuracy = accuracy_score(y_train, y_train_pred)
test_accuracy = accuracy_score(y_test, y_test_pred)
print('The training accuracy is', train_accuracy)
print('The test accuracy is', test_accuracy)

The training accuracy is 0.8707865168539326
The test accuracy is 0.8547486033519553


## Performance  Measures 

### Implementing cross validation 

**Cross validation means take samples and calculate accuracy for each sample and analysis that model underfit or overfit**

In [21]:
# calculate cross validation score on training dataset to checke model are underfit or not?
from sklearn.model_selection import cross_val_score

cross_val_score(model, X_train, y_train, cv=5, scoring = 'accuracy')

array([0.7972028 , 0.81818182, 0.79577465, 0.79577465, 0.80985915])

In the above, you can see that accuracies of five samples are good and hence model isn't underfit.

In [22]:
# calculate cross validation score on testing dataset and compaire with training 
# crsoss validation score that model are overfiting or not?

cross_val_score(model, X_test, y_test, cv = 5, scoring='accuracy')

array([0.66666667, 0.86111111, 0.72222222, 0.69444444, 0.82857143])

In above you can see and compaire testing cross validation score to traing cross validation score, score are good and no more difference. it's good for generalization and hence model isn't overfit.

## Confusion Matrix

[Refrence](https://wiki.pathmind.com/accuracy-precision-recall-f1#:~:text=That%20is%2C%20a%20good%20F1,total%20failure%20when%20it's%200%20.)

1.  **Accuracy** : accuracy tell us that wether model is trained correctly with x% percent.

2. **Precision** : Precision says, what propocertion of the positive identification are actually correct?

3. **Recall (sensitivity)** : Recall says, what propocertion of actual positive are identified correctly? it's also called **senitivity**, true positive rate and hit rate.
4. **F1 score** : F1 score measure the overall accuracy that combines precition and recall. Good F1 score mean, low **false positive rate** and low false negative rate.
Note:- recall measure the **true postive rate**. F1 score **1** means perfect model and F1 score **0** mean failure model.

5. **Specificity** :  Specificity also known as **true negative rate**, say that what proportion of actual negatives are correctly identify.

## Predict `y values` using cross validation and evalute model using confusion matrix

In [23]:
from sklearn.model_selection import cross_val_predict

y_train_pred = cross_val_predict(model, X_train, y_train, cv = 5)

In [24]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_train, y_train_pred)

array([[399,  45],
       [ 95, 173]])

In above, confusion_matrix return a confusion matrix in which each rows represent **actual value** and each columns represent **predicted values**.

see below:- 
                                          
                                          Predicted values
                                         
                                         No              Yes
                          --------------------------------------
                              No         TN               FP
              Actual values

                             Yes        FN               TP



### Calculate Accuracy, precision, Recall and Specifisity

In [25]:
tn, fp, fn, tp = confusion_matrix(y_train, y_train_pred).ravel()

tn, fp, fn, tp

(399, 45, 95, 173)

In [26]:
# Wow, Accuracy, precision are too good. accuracy tell us the accuracy of correct classify of true postive and true negative.

accuracy = (tp + tn) / (tp + tn + fp + fn)
accuracy

0.8033707865168539

In [27]:
precision = tp / (tp + fp)
precision

0.7935779816513762

In [28]:
# Recall is also known as sentitivity , `true positive rate`

recall = tp / (tp + fn)
recall

0.6455223880597015

In [29]:
# F1 score is also good with 71% that tell us our model has perfectly train for generalization

F1_score = 2 * (precision * recall) / (precision + recall)
F1_score

0.7119341563786009

In [30]:
# Specificity is also known as `true negative rate`
specificity = tn / (tn + fp)
specificity

0.8986486486486487

In model evaluation of the classification problem, the main goal is, the has good true positive rate with keeping low false positive rate. you can see our model is as expected.

In [31]:
# we can calculate false positive rate 1 minus true negative rate
false_posive_rate = 1 - specificity
false_posive_rate

0.10135135135135132

## Model Evaluation on testing dataset

I'm using predefine function to calculate accuracy, precision, recall and specifity.

In [32]:
from sklearn.metrics import  confusion_matrix, precision_score, recall_score, f1_score

y_test_pred = cross_val_predict(model, X_test, y_test, cv = 5 )

In [33]:
confusion_matrix(y_test, y_test_pred)

array([[83, 22],
       [22, 52]])

In [34]:
accuracy_score(y_test, y_test_pred)

0.7541899441340782

In [35]:
precision_score(y_test, y_test_pred)

0.7027027027027027

In [36]:
recall_score(y_test, y_test_pred)

0.7027027027027027

In [37]:
f1_score(y_test, y_test_pred)

0.7027027027027027

In [38]:
precision_score(y_test, y_test_pred)

0.7027027027027027

In [39]:
recall_score(y_test, y_test_pred)

0.7027027027027027

In [40]:
f1_score(y_test, y_test_pred)

0.7027027027027027